# Generated by Django 3.1.1 on 2020-09-15 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_list',
            field=models.TextField(default=''),
        ),
    ]
