# Generated by Django 3.1.1 on 2020-09-15 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20200915_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_list',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='lists.list'),
        ),
    ]
